### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by anes66** [BuyLabs/BodgedRadio-PMA#1]
First of all thank you for sharing it with us :)

Is it possible to make privat channels for PD EMS and Mehanic or all channels accesable for every player?

**Comment by tencreator** [comment]
Not to my knowledge this would normally be done with something like ESX or the voice chat itself not the radio and to my knowledge PMA voice does not support this currently but if that comes out with PMA then you should be fine but for now if you really want private channels for EMS and PD then I recommend discord but I shall look into making a ESX version of this radio and making lockable channels.

**Comment by tencreator** [comment]
Do watch out on [my webstore](https://san-andreas-state-roleplay-webshop.tebex.io/category/cat-development) as I am currently converting GCPhone to work with PMA-Voice

**Comment by tencreator** [comment]
If you want to test out ether of these go to 
[our discord](https://discord.gg/sasrp)
or
[Click here to join the server automatically ](https://cfx.re/join/84kabm)
